### ISSUE TITLE
Crash on 0.12 while copying PGP data to the clipboard

### ISSUE THREAD

**Issue by ibanferreira** [Mnkai/PGPClipper#6]
Hello, 

Sorry to be a killjoy here but every time I copy PGP data to the clipboard the app crashes. 

https://gist.github.com/anonymous/11ea2270437716cecb60

**Comment by Mnkai** [comment]
Sorry for the trouble, this bug is already fixed in commit b715f6edbb791e5e51b37b441f79eee75b533a2e.

This change will be applied in public 0.2 release - which should be released within few days, or you can also compile this app yourself for faster troubleshooting.

This issue will be closed once I really confirm that this fix is working.

**Comment by ibanferreira** [comment]
Cool, thanks, I am looking forward for the new release then.

**Comment by Mnkai** [comment]
Looks like this issue is fixed, as referenced that decryption is successful in issue #8. I'll close this one.
